FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt .
RUN cat requirements.txt && pip install -v --no-cache-dir -r requirements.txt

COPY . .
CMD ["python", "-u", "ingestion_delphi.py"]
